# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(0F0F12)
$foreground = rgb(C0C6DA)
$color0 = rgb(3A3A3C)
$color1 = rgb(484750)
$color2 = rgb(484851)
$color3 = rgb(4B4B56)
$color4 = rgb(504F5E)
$color5 = rgb(687296)
$color6 = rgb(6C7AA9)
$color7 = rgb(9CA5C2)
$color8 = rgb(6D7487)
$color9 = rgb(484750)
$color10 = rgb(484851)
$color11 = rgb(4B4B56)
$color12 = rgb(504F5E)
$color13 = rgb(687296)
$color14 = rgb(6C7AA9)
$color15 = rgb(9CA5C2)
