# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(1A1B26)
$foreground = rgb(A9B1D6)
$color0 = rgb(13141C)
$color1 = rgb(F7768E)
$color2 = rgb(9ECE6A)
$color3 = rgb(E0AF68)
$color4 = rgb(7AA2F7)
$color5 = rgb(AD8EE6)
$color6 = rgb(449DAB)
$color7 = rgb(A9B1D6)
$color8 = rgb(565F89)
$color9 = rgb(FF7A93)
$color10 = rgb(B9F27C)
$color11 = rgb(FF9E64)
$color12 = rgb(7DA6FF)
$color13 = rgb(BB9AF7)
$color14 = rgb(0DB9D7)
$color15 = rgb(C0CAF5)
