# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(2D353B)
$foreground = rgb(D3C6AA)
$color0 = rgb(21272C)
$color1 = rgb(E67E80)
$color2 = rgb(A7C080)
$color3 = rgb(DBBC7F)
$color4 = rgb(7FBBB3)
$color5 = rgb(D699B6)
$color6 = rgb(83C092)
$color7 = rgb(D3C6AA)
$color8 = rgb(4F585E)
$color9 = rgb(E67E80)
$color10 = rgb(A7C080)
$color11 = rgb(DBBC7F)
$color12 = rgb(7FBBB3)
$color13 = rgb(D699B6)
$color14 = rgb(83C092)
$color15 = rgb(D3C6AA)
