# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #

#environment-variables
env = CLUTTER_BACKEND,wayland
env = GDK_BACKEND,wayland,x11
env = QT_AUTO_SCREEN_SCALE_FACTOR,1
env = QT_QPA_PLATFORM,wayland;xcb
env = QT_QPA_PLATFORMTHEME,qt6ct 
env = QT_SCALE_FACTOR,1
env = QT_WAYLAND_DISABLE_WINDOWDECORATION,1
env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland
env = QT_SCALE_FACTOR_ROUNDING_POLICY,RoundPreferFloor
env = EDITOR, nvim
# vulkan
#env = WLR_RENDERER,vulkan
env = GDK_SCALE,1 
# firefox
env = MOZ_ENABLE_WAYLAND,1

# electron >28 apps (may help)
env = ELECTRON_OZONE_PLATFORM_HINT,auto

# Add ~/.local/bin to PATH so symlinks for swww work
env = PATH,$HOME/.local/bin:$PATH
