#!/usr/bin/env python3

# Waybar pill text colours, chosen per palette colour instead of hardcoded.
#
# The style assigns each pill a wallust colour as its background but a fixed
# @foreground or @color0 as its text. Wallust palettes change with every
# wallpaper and theme, so a fixed choice is unreadable whenever the background
# lands near the text colour. This reads the generated palette and writes an
# @on-<colour> for each one, picking whichever candidate has the best WCAG
# contrast against it.
#
# Run after wallust; the style imports the result.

import os
import re
import sys

PALETTE = os.path.expanduser("~/.config/waybar/wallust/colors-waybar.css")
OUT = os.path.expanduser("~/.config/waybar/wallust/contrast.css")
MIN_RATIO = 4.5


def luminance(hex_colour):
    r, g, b = (int(hex_colour[i:i + 2], 16) / 255 for i in (1, 3, 5))

    def channel(c):
        return c / 12.92 if c <= 0.03928 else ((c + 0.055) / 1.055) ** 2.4

    return 0.2126 * channel(r) + 0.7152 * channel(g) + 0.0722 * channel(b)


def ratio(a, b):
    la, lb = luminance(a), luminance(b)
    hi, lo = max(la, lb), min(la, lb)
    return (hi + 0.05) / (lo + 0.05)


def main():
    try:
        css = open(PALETTE).read()
    except OSError:
        return 1

    colours = dict(re.findall(r"@define-color\s+(\S+)\s+(#[0-9A-Fa-f]{6})", css))
    if not colours:
        return 1

    # Prefer the palette's own extremes so the bar stays in-theme, and fall back
    # to plain black/white only when neither clears the threshold.
    candidates = [c for c in (colours.get("color0"), colours.get("foreground")) if c]
    candidates += ["#101010", "#f5f5f5"]

    lines = [
        "/* generated by gen-contrast.sh - do not edit */",
        "/* readable text colour for each palette colour */",
        "",
    ]

    for name, value in sorted(colours.items()):
        best = max(candidates, key=lambda c: ratio(value, c))
        lines.append(f"@define-color on-{name} {best};")

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w") as fh:
        fh.write("\n".join(lines) + "\n")

    if "--verbose" in sys.argv:
        for name, value in sorted(colours.items()):
            best = max(candidates, key=lambda c: ratio(value, c))
            print(f"{name:12} {value}  -> {best}  ({ratio(value, best):.2f}:1)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
