# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #C0C6DA
background         #0F0F12
cursor             #696C7C

active_tab_foreground     #0F0F12
active_tab_background     #C0C6DA
inactive_tab_foreground   #C0C6DA
inactive_tab_background   #0F0F12

active_border_color   #C0C6DA
inactive_border_color #0F0F12
bell_border_color     #484750

color0      #3A3A3C
color1		#484750
color2		#484851
color3		#4B4B56
color4		#504F5E
color5		#687296
color6		#6C7AA9
color7		#9CA5C2
color8		#6D7487
color9		#484750
color10		#484851
color11		#4B4B56
color12		#504F5E
color13		#687296
color14		#6C7AA9
color15		#9CA5C2