# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #FAFCFB
background         #0C0B0C
cursor             #B59790

active_tab_foreground     #0C0B0C
active_tab_background     #FAFCFB
inactive_tab_foreground   #FAFCFB
inactive_tab_background   #0C0B0C

active_border_color   #FAFCFB
inactive_border_color #0C0B0C
bell_border_color     #C38B7B

color0      #090809
color1		#C38B7B
color2		#87A9B0
color3		#6B5E73
color4		#B59790
color5		#C4D8E2
color6		#A5A0B6
color7		#FAFCFB
color8		#584E51
color9		#C38B7B
color10		#87A9B0
color11		#6B5E73
color12		#B59790
color13		#C4D8E2
color14		#A5A0B6
color15		#E2DDDC