# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #B8CAD2
background         #141619
cursor             #637C8A

active_tab_foreground     #141619
active_tab_background     #B8CAD2
inactive_tab_foreground   #B8CAD2
inactive_tab_background   #141619

active_border_color   #B8CAD2
inactive_border_color #141619
bell_border_color     #45525D

color0      #3E4144
color1		#45525D
color2		#455E6E
color3		#5C7F8E
color4		#827DA6
color5		#61899A
color6		#61899A
color7		#91ABB6
color8		#65777F
color9		#45525D
color10		#455E6E
color11		#5C7F8E
color12		#827DA6
color13		#61899A
color14		#61899A
color15		#91ABB6