#  ┳┳┓┏┓┏┳┓┳┳┏┓┏┓┳┓  ┏┓┏┓┏┓┏┳┓
#  ┃┃┃┣┫ ┃ ┃┃┃┓┣ ┃┃━━┣ ┃┃┃┃ ┃ 
#  ┛ ┗┛┗ ┻ ┗┛┗┛┗┛┛┗  ┻ ┗┛┗┛ ┻ 
#                             


# -*- conf -*-
# Matugen

[colors]
alpha=1.0
background=101418
foreground=e0e2e8
regular0=101418
regular1=ffb4ab
regular2=9accfa
regular3=d2bfe7
regular4=cde5ff
regular5=d4e4f6
regular6=b9c8da
regular7=e0e2e8
bright0=36393e
bright1=ffb4ab
bright2=9accfa
bright3=d2bfe7
bright4=cde5ff
bright5=d4e4f6
bright6=b9c8da
bright7=e0e2e8
dim0=45475A 
dim1=F38BA8 
dim2=A6E3A1 
dim3=F9E2AF 
dim4=89B4FA 
dim5=F5C2E7 
dim6=94E2D5 
dim7=BAC2DE 
selection-foreground=9accfa
selection-background=003352

[cursor]
color=42474e e0e2e8
