#  ┳┳┓┏┓┏┳┓┳┳┏┓┏┓┳┓  ┏┓┏┓┏┓┏┳┓
#  ┃┃┃┣┫ ┃ ┃┃┃┓┣ ┃┃━━┣ ┃┃┃┃ ┃ 
#  ┛ ┗┛┗ ┻ ┗┛┗┛┗┛┛┗  ┻ ┗┛┗┛ ┻ 
#                             


# -*- conf -*-
# Matugen

[colors]
alpha=1.0
background=1a1110
foreground=f1dfdb
regular0=1a1110
regular1=ffb4ab
regular2=ffb4a8
regular3=dec48c
regular4=ffdad4
regular5=ffdad4
regular6=e7bdb6
regular7=f1dfdb
bright0=423735
bright1=ffb4ab
bright2=ffb4a8
bright3=dec48c
bright4=ffdad4
bright5=ffdad4
bright6=e7bdb6
bright7=f1dfdb
dim0=45475A 
dim1=F38BA8 
dim2=A6E3A1 
dim3=F9E2AF 
dim4=89B4FA 
dim5=F5C2E7 
dim6=94E2D5 
dim7=BAC2DE 
selection-foreground=ffb4a8
selection-background=561e16

[cursor]
color=534341 f1dfdb
